toolchain("aarch64-linux-musleabi")
    set_kind("standalone")
    set_sdkdir("$(projectdir)../../tools/gnu_gcc/aarch64-linux-musleabi_for_x86_64-pc-linux-gnu")
    on_load(function(toolchain)

	os.setenv("PROJ_DIR", os.projectdir())  --For lua embed build script
        toolchain:load_cross_toolchain()
        toolchain:set("toolset", "cc", "aarch64-linux-musleabi-gcc")
        toolchain:set("toolset", "cxx", "aarch64-linux-musleabi-g++")
	    -- add flags for arch
        toolchain:add("cxflags", "-march=armv7-a -marm -msoft-float -O0 -g -gdwarf-2  -Wall -n --static", {force = true})                                           
        toolchain:add("ldflags", "-march=armv7-a -marm -msoft-float -O0 -g -gdwarf-2  -Wall -n --static", {force = true})
        toolchain:add("ldflags", "-T $(projectdir)/../linker_scripts/aarch64/cortex-a/link.lds", {force = true})
        toolchain:add("ldflags", "-Wl,--whole-archive -lrtthread -Wl,--no-whole-archive", {force = true})
        toolchain:add("ldflags", "-Wl,--start-group -lrtthread -Wl,--end-group", {force = true})
        toolchain:add("linkdirs", "$(projectdir)/../sdk/rt-thread/lib/aarch64/cortex-a", {force = true})
        toolchain:add("includedirs", "$(projectdir)/../sdk/rt-thread/include", {force = true})
        toolchain:add("includedirs", "$(projectdir)/../sdk/rt-thread/components/dfs", {force = true})
        toolchain:add("includedirs", "$(projectdir)/../sdk/rt-thread/components/drivers", {force = true})
        toolchain:add("includedirs", "$(projectdir)/../sdk/rt-thread/components/finsh", {force = true})
        toolchain:add("includedirs", "$(projectdir)/../sdk/rt-thread/components/net", {force = true})
    end)
toolchain_end()
