option("plat")
    set_default("cross")
    set_showmenu(true)
    set_category("Target options")
    set_description("Compile for the given platform")
    set_values("linux", "windows", "cross")
option_end()

option("arch")
    set_default("arm")
    set_showmenu(true)
    set_category("Target options")
    set_description("Target Architecture")
    set_values("arm", "aarch64")
option_end()

option("toolchains")
    set_default("arm-linux-musleabi")
    set_showmenu(true)
    set_category("Target options")
    set_description("Target Compilation Toolchain")
    set_values("arm-linux-musleabi", "aarch64-linux-musleabi")
option_end()

option("host")
    set_default("arm-linux-musleabi")
    set_showmenu(true)
    set_category("Target options")
    set_description("Current host environment")
    set_values("arm-linux-musleabi", "aarch64-linux-musleabi")
option_end()

option("mode")
    set_default("debug")
    set_showmenu(true)
    set_category("Target options")
    set_description("Target build mode")
    set_values("debug", "release")
option_end()

option("kind")
    set_default("static")
    set_showmenu(true)
    set_category("Target options")
    set_description("Target build type")
    set_values("static", "shared", "binary")
option_end()

option("pic")
    set_default(true)
    set_showmenu(true)
    set_category("Target options")
    set_description("Target build static library")
    set_values(true, false)
option_end()
