option("arch")
    set_default("arm")
    set_showmenu(true)
    set_category("Target options")
    set_description("Target Architecture")
    set_values("arm", "aarch64")
option_end()

option("toolchains")
    set_default("arm-linux-musleabi")
    set_showmenu(true)
    set_category("Target options")
    set_description("Target Compilation Toolchain")
    set_values("arm-linux-musleabi", "aarch64-linux-musleabi")
option_end()

option("mode")
    set_default("debug")
    set_showmenu(true)
    set_category("Target options")
    set_description("Target build mode")
    set_values("debug", "release")
option_end()

option("type")
    set_default("static")
    set_showmenu(true)
    set_category("Target options")
    set_description("Target build type")
    set_values("static", "shared", "binary")
option_end()
